baseURL = "https://sketchthedocs.github.io/AB-See"
languageCode = "en-us"
title = "#ABSee | @SketchTheDocs"
theme = "hugo-swift-theme"

# Specify (new) Build directory
publishdir = "../docs" 

# ---- Customization ----

author = "Nitya Narasimhan"
copyright = "Copyright © 2021-present, Nitya Narasimhan; all rights reserved."
canonifyurls = true
paginate = 4

# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true


# ---- PARAMETERS ----

[params]

  [params.designer]
    name = "SketchTheDocs"
    url = "https://twitter.com/sketchthedocs/"

  [[params.authors]]
    # can be nickname 
    # if fullName 👇🏻 isn't set, name will be displayed on author card
    name = "nitya" 

    # optional. If set, it will display on author card
    fullName = "Nitya Narasimhan" 
    bio = "Hello World! #ABSee - using visual puzzles to build your tech IQ!"
    photo = "https://pbs.twimg.com/profile_images/1336782118924455944/K4ZDwHHg_400x400.png"
    url = "https://twitter.com/nitya"

    # google analytics ID e.g UA-116386578-1
    # ga_analytics = "UA-145095098-3" 
    # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
    # ga_verify = "" 

    # twitter = "@sketchthedocs" # twitter handle e.g @weru
    # logo = "logo.png"
    # author = "nitya" # default author
    # image = "placeholder-image.png" # used whenever a page image is not set

    # uncomment and edit to exclude normal pages ... see issue #57
    # blogDir = "blogFolderName" 

# [params.staticman]
    # URL of your own API deployment (without trailing slash), default: "https://staticman-frama.herokuapp.com"
    #   endpoint = ""  
    #   gitProvider = "github"  # Either "github" or "gitlab"
    #   username = "nitya"  # GitHub/GitLab user name
    #   repository = "https://github.com/SketchTheDocs/AB-See"  

    # Branch holding the source code for your site, 
    # should match the `branch` parameter in `staticman.yml`
    #   branch = "main"  
#
#   # If you use reCAPTCHA v2, you must also set these parameters in staticman.yml
#   [Params.staticman.reCaptcha]
#     siteKey = ""  # Use your own site key, you need to apply for one on Google
#     secret  = ""  # ENCRYPT your password by going to https://<staticman-endpoint>/v3/encrypt/<your-site-secret>

[menu]

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 2

  [[menu.main]]
    name = "Hello World"
    url = "helloworld/"
    weight = 3

  [[menu.main]]
    name = "Puzzles"
    url = "puzzles/"
    weight = 4

  [[menu.main]]
    name = "Categories"
    url = "categories/"
    weight = 5

  [[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 6